name: Deploy to Docker

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      # - name: Run Docker container
      #   run: |
      #     docker run -e API_KEY=${{ secrets.API_KEY }} \
      #                -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
      #                -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
      #                my-docker-image
