name: Deploy to Docker

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Docker container
        run: |
          docker run -e API_KEY=${{ secrets.API_KEY }} \
                     -e WANTED_API_KEY=${{ secrets.WANTED_API_KEY }} \
                     -e WANTED_API_KEY_2=${{ secrets.WANTED_API_KEY_2 }} \
                     -e API_KEY_SAMANTA=${{ secrets.API_KEY_SAMANTA }} \
                     -e DEF_KEY=${{ secrets.DEF_KEY }} \
                     my-docker-image
